### ISSUE TITLE
Calendar back button doesn't work properly

### ISSUE THREAD

**Issue by jcub** [rpiambulance/website#14]
Should bring back to previous view, not to current date.

**Comment by MasterOdin** [comment]
So to fix this, probably the best solution would be to add a ng-click function ("updateDate") to the previous/next buttons on each view. They would then have a setup like:

```
$scope.updateDate = function() {
    $location.search('viewDate', $scope.viewDate);
};
```

Then, when the date is set on the initial page load, do a check to see if viewDate exists within `$location.search()` and if so, then use that for the starting value of viewDate (`$scope.viewDate = $location.search()['viewDate'] || new Date()`)

You will also need to add:
```
    $routeProvider.when('/games-events', {
        templateUrl: 'views/games-events.html',
        controller: 'GamesEventsCtrl',
        caseInsensitiveMatch: true,
        reloadOnSearch: false,
        activeTab: 'games-events',
        title: 'Games Events',
    });
```

to appRoutes.js
