### ISSUE TITLE
#103 is incomplete

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/website#158]
#103, which dealt with a bylaws page, appears incomplete. There is no navbar link for bylaws, and the page itself (https://rpiambulance.com/#/bylaws) has an iframe that 404s.

**Comment by tceluzza** [comment]
The correct embed folder ID should be `1dNnyB9imWyOB6-1j-hQeiDXv0xqUTMaX`

**Comment by CKegel** [comment]
I'll patch it this weekend, ideally before the GBM
