### ISSUE TITLE
Provide an option to file a grievance on the website

### ISSUE THREAD

**Issue by CKegel** [rpiambulance/website#173]
Provide a web form so members can file a grievance report directly from the website. We could complete this with an embeded google form or a custom web form.

**Comment by alexmattoni** [comment]
Do we think this page would be more appropriate to go under "Tools" or under "Resources"?

**Comment by alexmattoni** [comment]
I think 'Tools' is the way to go with how busy 'Resources' is, and since it's a fillable form (like the fuel log or stocking forms). Idc either way.

**Comment by CKegel** [comment]
I agree - "Tools' definitely makes more sense
