### ISSUE TITLE
Invalid Captcha Domain

### ISSUE THREAD

**Issue by bryan-johns** [rpiambulance/website#2]
The captcha is unusable on multiple pages, and is giving the error:
ERROR for site owner:
Invalid domain for site key

![image](https://user-images.githubusercontent.com/19780692/30280964-2209e102-96df-11e7-94c0-ea46fdf7a073.png)

![image](https://user-images.githubusercontent.com/19780692/30280998-365c5234-96df-11e7-836f-7692a25e4451.png)

![image](https://user-images.githubusercontent.com/19780692/30281027-4f0ac7f2-96df-11e7-9e2d-2491ce627967.png)

**Comment by lramos15** [comment]
I checked all the forms which I could find a reCAPTCHA and they all seem to be working. Let me know if you find one that isn't.
